### ISSUE TITLE
Unexpected memory growth

### ISSUE THREAD

**Issue by luke-clifton** [HeinrichApfelmus/reactive-banana#253] opened 2022-03-25 00:40 UTC
The following simplified code seems to leak memory. Manually running a major GC after every `fireTick ()` does not solve the problem.

I'm using 054781d0b0bf4e43ec1f395e3ccdbe7c7bd25896

```haskell
main :: IO ()
main = do
    (tickHandler, fireTick) <- newAddHandler
    let
        networkDescription :: MomentIO ()
        networkDescription = do
            tick <- fromAddHandler tickHandler
            x <- switchE tick (tick <$ tick)
            reactimate (print () <$ x)
            pure ()
    net <- compile networkDescription
    actuate net
    replicateM_ 50000 $ do
        fireTick ()
```

![image](https://user-images.githubusercontent.com/6327304/160031676-5103fef1-0a61-4758-9ef3-67e4b0dd8dc8.png)

**Comment by ocharles** [comment] 2022-03-25 08:41
Nice catch! I've been wanting to play with the new info table profiling in GHC 9.2, maybe I can figure out what's going on!

**Comment by ocharles** [comment] 2022-03-28 21:29
This may be a duplicate of https://github.com/HeinrichApfelmus/reactive-banana/issues/152

**Comment by luke-clifton** [comment] 2022-03-29 09:49
Hmm it looks the same yes. Though I thought I'd tried it with `never`, and not seen the growth. I'm double check that later.

**Comment by ocharles** [comment] 2022-03-29 09:51
Yea, this is a bit different due to the event switching into itself. I really want to get this fixed, but it's surprisingly tricky! I'm hoping I can use `ghc-debug` to visualize the heap and understand who's keeping what alive.

**Comment by luke-clifton** [comment] 2022-03-29 13:14
Just noticed you can comment out the `reactimate` and you still get the growth. (Which is perhaps a different bug?)

If I use `never` then I do see the growth with the `reactimate` and no growth without it.

**Closed** 2022-06-16 07:12 UTC
