### ISSUE TITLE
How can this library be installed with stack on macOS?

### ISSUE THREAD

**Issue by 2426021684** [HeinrichApfelmus/reactive-banana#144] opened 2017-02-11 01:27 UTC
I am using stack on macOS Sierra. How can I install this library? Adding reactive-banana-wx to extra-deps gives an error but no information about why the build failed.

**Comment by ocharles** [comment] 2017-02-12 11:26
Could you provide a full log?

**Comment by 2426021684** [comment] 2017-02-12 15:20
http://lpaste.net/8538512301479690240

**Comment by jdreaver** [comment] 2017-02-12 16:00
It looks like the problem is with `wxcore`.

**Comment by 2426021684** [comment] 2017-02-12 17:34
https://sourceforge.net/p/wxhaskell/bugs/109/

**Comment by HeinrichApfelmus** [comment] 2017-08-07 12:46
Closing this, as the problem appears to be with installing a dependency (`wxcore`). Sorry that I can't do much about it.

**Closed by HeinrichApfelmus** 2017-08-07 12:46 UTC
Labels: Type: Maintenance
